# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

include ./gruvbox.conf

# font
font_family       Hack Regular Nerd Font Complete Mono
bold_font 		    Hack Bold Nerd Font Complete Mono 
italic_font 		  Hack Italic Nerd Font Complete Mono
bold_talic_font		Hack Bold Italic Nerd Font Complete Mono

# font size (pts)
font_size 10.0
font_size_delta	2
font_ltr  no
disable_ligatures never

# cursor
cursor_blinking_interval  0.4
cursor_stop_blinking_after  5.0
cursor_shape  block

# mouse
mouse_hide_wait	3.0

# double click detection
click_interval	0.5

# don't care, use i3
focus_follows_mouse	yes
enabled_layouts		*
remember_window_size	no
initial_window_width	640
initial_window_height	400

# window decorations
window_border_width	1
window_padding_width	0
active_border_color	#0f0
inactive_border_color	#ccc

# tab-bar colors
active_tab_foreground	#000
active_tab_background	#eee
inactive_tab_foreground	#444
inactive_tab_background	#999

# bell
visual_bell_duration	0.1
enable_audio_bell	no

