[colors]
background = #282828
foreground = #ebdbb2
red        = #fb4934
green      = #b8bb26
yellow     = #fabd2f
blue       = #83a598
purple     = #d3869b
teal       = #8ec07c
orange     = #fe8019
gray       = #a89984

[bar/mainscreen]
; Size
width  = 100%
height = 25


; Position
top = true

; Radius

; Align modules fixed to middle
fixed-center = true

; Colors
background = ${colors.background}
foreground= ${colors.foreground}

; Underline
line-size  = 2
line-color = ${colors.foreground}

; Border
border-size  = 0
border-color = ${colors.background}

; Padding
padding-left  = 0
padding-right = 0

; Margin of modules
module-margin-left  = 0
module-margin-right = 0

; Font
font-0 = "Hack:size=10"

; Modlues
modules-left   = i3
modules-center = time date
modules-right  = netowrk pulseaudio

; Cursor actions
cursor-click  = pointer
cursor-scroll = ns-resize

; Tray
tray-position = right


[module/i3]
type = internal/i3

; Mouse click
enable-click = true

; Mouse scroll
enable-scroll = false

; Sort
index-sort = true

; Display icons
fuzzy-match = true


; Icons
ws-icon-0       = Main;
ws-icon-1       = Terminal;
ws-icon-2       = Web;
ws-icon-3       = Program;
ws-icon-4       = Design;
ws-icon-default = 

; Focused label
label-focused            = %name%
label-focused-underline  = ${colors.orange}
label-focused-foreground = ${colors.foreground}
label-focused-padding    = 1

; Unfocused labels
label-unfocused            = %name%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding    = 1

; Visible labels
label-visible            = %name%
label-visible-foreground = ${colors.foreground}
label-visible-padding    = 1

; Urgent labels
label-urgent            = %name%
label-urgent-foreground = ${colors.red}
label-urgent-padding    = 1

[module/time]
type = internal/date

; Update interval
interval = 1.0

; Format
time = %H:%M:%S

; Label
label            =  %time%
label-foreground = ${colors.foreground}
label-padding    = 1

[module/date]
type = internal/date

; Update interval
interval = 1.0

; Format
date = %A, %d %B

; Label
label            =  %date%
label-foreground = ${colors.foreground}
label-padding    = 1


[module/network]
type = internal/network
; Name of the network interface to display. You can get the names of the
; interfaces on your machine with `ip link`
; Wireless interfaces often start with `wl` and ethernet interface with `eno` or `eth`
interface = enp0s20f0u6

; If no interface is specified, polybar can detect an interface of the given type.
; If multiple are found, it will prefer running interfaces and otherwise just
; use the first one found.
; Either 'wired' or 'wireless'
; New in version 3.6.0
interface-type = wired

; Seconds to sleep between updates
; Default: 1
interval = 3.0

; Test connectivity every Nth update
; A value of 0 disables the feature
; NOTE: Experimental (needs more testing)
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have 
; an unknown state, even when they're running
; Default: false
unknown-as-up = true

; The unit used for displaying network speeds
; For example if set to the empty string, a speed of 5 KB/s is displayed as 5 K
; Default: B/s
; New in version 3.6.0
speed-unit = ''



